export const SecurityQuestions: string[] = [
  "What is your mother's maiden name?",
  "What is your favorite color?",
  "What is your favorite animal?",
  "What was the name of your first pet?",
  "What is your favorite book?",
  "What was your high school mascot?",
  "What is your favorite food?",
  "What is your favorite movie?",
  "What is your favorite song?",
  "What is the name of the street you grew up on?",
  "What is your favorite hobby?",
  "What was the make and model of your first car?",
  "What is your favorite sports team?",
  "What was your favorite subject in school?",
  "What is your favorite vacation spot?",
  "What is the name of the hospital where you were born?",
  "What is your favorite TV show?",
  "What was the name of your childhood best friend?",
  "What is your favorite type of cuisine?",
  "What is your favorite video game?",
];
