// export interface InsurancePolicy {
//   giaArNo: string;
//   giaArDate: Date;
//   insurerOrNo: string;
//   insurerOrDate: Date;
//   giaOrNo: string;
//   giaOrDate: Date;
//   sa: string;
//   insurer: string;
//   assured: string;
//   mailingAddress: string;
//   locationOfRisk: string;
//   policy: string;
//   issuedDate: Date;
//   inception: Date;
//   expiry: Date;
//   particulars: string;
//   plate: string;
//   sumInsured: number;
//   premium: number;
//   lgt: number;
//   vat: number;
//   dst: number;
//   otherCharges: number;
//   totalAmount: number;
//   line: string;
//   deductible: number;
//   serial: string;
//   chassisNo: string;
//   mvFile: string;
//   mortgagee: string;
//   color: string;
//   od: number;
//   theft: number;
//   vBi: number;
//   vPd: number;
//   autoPA: number;
//   aog: number;
//   rscc: number;
//   lossOfUse: number;
//   odPrem: number;
//   theftPrem: number;
//   vBiPrem: number;
//   vPdPrem: number;
//   autoPAPrem: number;
//   aogPrem: number;
//   lossOfUsePrem: number;
//   accidentalDeathOrDismemberment: number;
//   medicalExpenses: number;
//   uma: number;
//   building1: number;
//   building2: number;
//   contents1: number;
//   contents2: number;
//   others: number;
//   invoiceNoMarineOnly?: string;
//   blNoMarineOnly?: string;
//   remarks1?: string;
//   remarks2?: string;
//   remarks3?: string;
//   remarks4?: string;
//   etc1?: string;
//   etc2?: string;
// }

export interface InsurancePolicyOld {
  sa: string;
  insurer: string;
  assured: string;
  address: string;
  policy: string;
  issueDate: string;
  inception: string;
  expiry: string;
  modelMakeRisk: string;
  plate: string;
  sumInsured: string;
  totalPrem: string;
  grossPrem: string;
  deductible: string;
  serial: string;
  motor: string;
  mvFile: string;
  od: string;
  theft: string;
  vbi: string;
  vpd: string;
  autoPa: string;
  aog: string;
  lossOfUse: string;
  odPrem: string;
  theftPrem: string;
  vBiOrPrem: string;
  vPdOrPrem: string;
  autoPaOrPrem: string;
  aogOrPrem: string;
  lossOfUseOrPrem: string;
  _id?: string;
  updatedAt?: string;
  creator?: string;
}

export interface InsurancePolicy {
  issueDate: string;
  inception: string;
  expiry: string;
  giaArDate: string;
  insurerOrDate: string;
  giaOrDate: string;
  serial: string;
  policy: string;
  sa: string;
  insurer: string;
  assured: string;
  address?: string;
  modelMakeRisk?: string;
  plate?: string;
  totalPrem?: string;
  grossPrem?: string;
  deductible?: string | number;
  motor?: string;
  mvFile?: string;
  od?: string | number;
  theft?: string | number;
  vbi?: string;
  vpd?: string;
  autoPa?: string;
  aog?: string;
  lossOfUse?: string;
  odPrem?: string | number;
  theftPrem?: string | number;
  vBiOrPrem?: string;
  vPdOrPrem?: string;
  autoPaOrPrem?: string;
  aogOrPrem?: string;
  lossOfUseOrPrem?: string;
  _id?: string;
  updatedAt?: string;
  updatedByAgentName?: string;
  updatedByAgent: string;
  creator?: string;
  giaArNo?: string;
  insurerOrNo?: string;
  giaOrNo?: string;
  mailingAddress?: string;
  locationOfRisk?: string;
  particulars?: string;
  sumInsured?: number;
  premium?: number;
  lgt?: number;
  vat?: number;
  dst?: number;
  otherCharges?: number;
  totalAmount?: number;
  line?: string;
  chassisNo?: string;
  mortgagee?: string;
  color?: string;
  vBi?: number;
  vPd?: number;
  autoPA?: number;
  aogPrem?: number;
  lossOfUsePrem?: number;
  vBiPrem?: number;
  vPdPrem?: number;
  autoPAPrem?: number;
  rscc?: number;
  accidentalDeathOrDismemberment?: number;
  medicalExpenses?: number;
  uma?: number;
  building1?: number;
  building2?: number;
  contents1?: number;
  contents2?: number;
  others?: number;
  invoiceNoMarineOnly?: string;
  blNoMarineOnly?: string;
  remarks1?: string;
  remarks2?: string;
  remarks3?: string;
  remarks4?: string;
  etc1?: string;
  etc2?: string;
}
